### ISSUE TITLE
When will you release the source code?

### ISSUE THREAD

**Issue by LiiiAJ** [SBCV/SatelliteSurfaceReconstruction#1]
Excuse me, I read your paper and found that the effect is very good. I like the effect very much. When will you release the source code? I want to learn more from you, if you can release the source code, I am grateful and thank you very much! Please help me!

**Comment by SBCV** [comment]
We are currently refactoring the source code and adding some documentation. Overall, I think this should be done within the next three weeks.

**Comment by SBCV** [comment]
Source code has been released - closing this  issue
