### ISSUE TITLE
extraction_pipline

### ISSUE THREAD

**Issue by xinyun12836** [SBCV/SatelliteSurfaceReconstruction#6]
data_extraction the pan_image and msi_image,the two names are differen.such as 
0000_WV03_14NOV15_135121-P1BS-500171606160_05_P005.png
0000_WV03_15JAN23_134652-M1BS-500497282020_01_P001.png

**Comment by SBCV** [comment]
Can you describe the problem with more details?
At which point does the pipeline not work? Can you link the corresponding line in the source code?

**Comment by xinyun12836** [comment]
您好！邮件收到，我将尽快给您回复。

**Comment by SBCV** [comment]
I do not speak Chinese, so please keep the conversation in English.

**Comment by xinyun12836** [comment]
Thank you！ I found that the problem was caused by incomplete image data.

**Comment by xinyun12836** [comment]
您好！邮件收到，我将尽快给您回复。
